### ISSUE TITLE
Create the option to only allow responses from logged-in users (student login)

### ISSUE THREAD

**Issue by lprisan** [centre-for-educational-technology/la_pills#12]
This includes:
* ~Selector in create session page "allow anonymous responses"~
* ~Kick anonymous users to login page, if not allowed (including message/explanation)~
  * ~Make sure that user is redirected to the Session Entity main view page after login~
* ~Adding userid to the responses table~
* ~... and update downloadable csv as well~

Issues to be discussed:
     * ~Take away most permissions from teacher (only create session and provide answers), and students (only provide answers)~
* ~How to deal with GDPR, right to be forgotten…?~

**Comment by pjotrsavitski** [comment]
Please note that the basic logic for redirection to login page is already implemented, though it does need refactoring with regards to providing a centralised solution and also a way to redirect user to a page that triggered the initial action.

**Comment by pjotrsavitski** [comment]
Student account is assumed to be an authenticated user. Teacher account could have any name assigned to it. [README](https://github.com/centre-for-educational-technology/la_pills/blob/master/README.md#usage-and-running-in-development) file has instructions for doing that (the specifics of roles and permissions is up to the system administrator).

**Comment by pjotrsavitski** [comment]
Moved the GDPR part to the separate issues #21
