### ISSUE TITLE
Nickname-based student authentication

### ISSUE THREAD

**Issue by lprisan** [centre-for-educational-technology/la_pills#18]
... as a third option in the session creation/configuration
It would also require some extra step/screen somewhere before the student can access the session page and respond questionnaires (and maintaining it during the session, with a cookie or sthg)

**Comment by pjotrsavitski** [comment]
This one seems to be a standard case for unauthenticated user with possibility to enter a name that would be stored somewhere. Some logic on when should that be asked and how would it work is required.

**Comment by lprisan** [comment]
Yes, it would complicate the logic a little bit. I guess it would be sort of a login screen (or modal window) before getting to the session page (and the nickname would be stored in cookies, I guess?)

I wonder if we should wait for this until we know we really need this kind of authentication (from the use cases, at the start of April)...

**Comment by pjotrsavitski** [comment]
Well, it could be some JS based solution that would show the dialog/overlay. Would it be required or optional? We could also ask that one when user would try to answer the questionnaire for the first time and then show that somewhere once that has been entered.

It would probably be stored within the cookie, although there might also be some other storage solution that would only store the value for the duration of a session (cookies do not expire with the session, unless that is the session cookie itself).

**Comment by lprisan** [comment]
Required vs. optional: If the teacher selects "nickname authentication" when creating the session (vs. anonymous or authenticated), then the nickname should be mandatory. Otherwise, not present at all?

When the nickname should expire: not sure, probably as much as the session?
