### ISSUE TITLE
Numeric code redirection for student access to sessions

### ISSUE THREAD

**Issue by lprisan** [centre-for-educational-technology/la_pills#19]
Probably should be somewhere big and bold in the front page, for students to use easily
The idea can be seen in action in https://kahoot.it/ , for example

**Comment by pjotrsavitski** [comment]
What should be done in scenarios when authenticated user is required? Current logic would redirect the user to the login screen.

What should be the place where teacher/admin/owner would see the code?

**Comment by lprisan** [comment]
Redirecting to the login screen would make sense in the case of required authentication

I guess the easiest way to display the code would be displayed in the main session page, somewhere prominently (we can work on the visuals later :))

**Comment by pjotrsavitski** [comment]
OK. I suppose that it should be applicable to all the sessions and the unique code should be generated during the time of Session Entity creation?

**Comment by lprisan** [comment]
Yep, sounds good.
