### ISSUE TITLE
Provide some kind of session kill button for nickname-based login?

### ISSUE THREAD

**Issue by lprisan** [centre-for-educational-technology/la_pills#20]

**Comment by pjotrsavitski** [comment]
This is a side effect of creating a session for anonymous user. The session cookie will be present for the duration provided within the configuration of the Drupal instance. With no apparent way to get rid of it for the anonymous user.

The name provided would also be present for the duration of the session itself. The implementation is part of the issue #18

**Comment by pjotrsavitski** [comment]
Current implementation will reset the name, if present. But not the session.
