### ISSUE TITLE
Implement hooks for extending session entity view

### ISSUE THREAD

**Issue by lprisan** [centre-for-educational-technology/la_pills#25]
... exact method TBD with the Prolearning+Edulog contractors

**Comment by pjotrsavitski** [comment]
Implemented initial [hook](https://github.com/centre-for-educational-technology/la_pills/blob/master/session_entity.page.inc#L94) to allow extending the Session Entity main view.

Changed the [template](https://github.com/centre-for-educational-technology/la_pills/blob/master/templates/session-entity.html.twig#L41) for it to be included.

Added the [documentation](https://github.com/centre-for-educational-technology/la_pills/blob/master/la_pills.api.php) file that could be used as a reference for what parameters are available and how should the hooks be used.

**Comment by pjotrsavitski** [comment]
This one turned out to be not needed. Hooks would be added when needed.
